# Generated by Django 5.2 on 2025-05-06 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.inscripcion')),
            ],
        ),
    ]
